name: Java CI with Maven

on:
  push: 
    paths:
      - 'ActionsHiba/**'  # Directory for your project
  pull_request:
    paths:
      - 'ActionsHiba/**'  # Directory for your project

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file ActionsHiba/pom.xml  # Adjusted to your project directory

    - name: Run tests
      run: mvn test --file ActionsHiba/pom.xml  # Adjusted to your project directory
